Foreground yes
User clamav
DatabaseDirectory /var/lib/clamav
TemporaryDirectory /tmp
TCPSocket 3310
TCPAddr 0.0.0.0
StreamMaxLength 100M
MaxScanSize 100M
MaxFileSize 100M
MaxRecursion 16
MaxFiles 10000
MaxThreads 12
ReadTimeout 120
CommandReadTimeout 30
SendBufTimeout 120
ExitOnOOM yes
AlertEncrypted yes
LogTime yes
LogClean no
